package com.example;

import static org.junit.Assert.assertEquals;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.example.email.process.EmailCheck;

public class TestEmailCheck {

	    @Before
	    public void setUp() throws Exception {
	    }

	    @After
	    public void tearDown() throws Exception {
	    }
	   

	    @Test
	    public void validCheck1() {
	    	assertEquals(true, EmailCheck.INSTANCE.resolveEmailID("KNeKTM2yW2@live.com").isValid());
	    }
	    
	    @Test
	    public void validCheck2() {
	    	assertEquals("abcjk", EmailCheck.INSTANCE.resolveEmailID("aBCjK@live.com").getName());
	    }

	    @Test
	    public void validCheck3() {
	    	String emailID = "AbcHk+a23@live.com";
			assertEquals(true, EmailCheck.INSTANCE.resolveEmailID(emailID).isValid());
	    	assertEquals("abchk", EmailCheck.INSTANCE.resolveEmailID(emailID).getName());
	    	assertEquals("live.com", EmailCheck.INSTANCE.resolveEmailID(emailID).getDomain());
	    }
	    @Test
	    public void validCheck4() {
	    	String emailID = "AbcHk.a23@live.com";
			assertEquals(true, EmailCheck.INSTANCE.resolveEmailID(emailID).isValid());
	    	assertEquals("abchka23", EmailCheck.INSTANCE.resolveEmailID(emailID).getName());
	    	assertEquals("live.com", EmailCheck.INSTANCE.resolveEmailID(emailID).getDomain());
	    }
	    
	    @Test
	    public void validCheck5() {
	    	String emailID = "AbcHk.a23@live.com";
			assertEquals(true, EmailCheck.INSTANCE.resolveEmailID(emailID).isValid());
	    	assertEquals("abchka23", EmailCheck.INSTANCE.resolveEmailID(emailID).getName());
	    	assertEquals("live.com", EmailCheck.INSTANCE.resolveEmailID(emailID).getDomain());
	    }
	    
	    @Test
	    public void validCheck6() {
	    	String emailID = "A.bcHk.a23@live.com";
			assertEquals(true, EmailCheck.INSTANCE.resolveEmailID(emailID).isValid());
	    	assertEquals("abchka23", EmailCheck.INSTANCE.resolveEmailID(emailID).getName());
	    	assertEquals("live.com", EmailCheck.INSTANCE.resolveEmailID(emailID).getDomain());
	    }
	    
	    @Test
	    public void validCheck7() {
	    	String emailID = "+A.bcHk.a23@live.com";
			assertEquals(false, EmailCheck.INSTANCE.resolveEmailID(emailID).isValid());
	    	assertEquals(null, EmailCheck.INSTANCE.resolveEmailID(emailID).getName());
	    	assertEquals(null, EmailCheck.INSTANCE.resolveEmailID(emailID).getDomain());
	    }
	    
	    @Test
	    public void validCheck8() {
	    	// too long. around 9k len
	    	String emailID = "qwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieu@live.com";
			assertEquals(false, EmailCheck.INSTANCE.resolveEmailID(emailID).isValid());
	    	assertEquals(null, EmailCheck.INSTANCE.resolveEmailID(emailID).getName());
	    	assertEquals(null, EmailCheck.INSTANCE.resolveEmailID(emailID).getDomain());
	    }
	    
	    @Test
	    public void validCheck9() {
	    	
	    	String emailID = "qwewertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiu@gmail.com";
	    	assertEquals(1001, emailID.length());
	    	
	    	assertEquals(false, EmailCheck.INSTANCE.resolveEmailID(emailID).isValid());
	    	assertEquals(null, EmailCheck.INSTANCE.resolveEmailID(emailID).getName());
	    	assertEquals(null, EmailCheck.INSTANCE.resolveEmailID(emailID).getDomain());
	    }
	    @Test
	    public void validCheck10() {
	    	
	    	String emailID = "qweertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiu@gmail.com";
	    	assertEquals(1000, emailID.length());
	    	
	    	assertEquals(true, EmailCheck.INSTANCE.resolveEmailID(emailID).isValid());
	    	assertEquals("qweertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiu", EmailCheck.INSTANCE.resolveEmailID(emailID).getName());
	    }
	    
	    @Test
	    public void validCheck11() {
	    	String emailID = "aÑ@live.com";
			assertEquals(false, EmailCheck.INSTANCE.resolveEmailID(emailID, false, false).isValid());
	    }
	    @Test
	    public void validCheck12() {
	    	String emailID = "aÑ@live.com";
			assertEquals(true, EmailCheck.INSTANCE.resolveEmailID(emailID, true, false).isValid());
	    }
	    @Test
	    public void validCheck13() {
	    	String emailID = "qwewertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiuoqieuqwoeuqowieuqwoeiqwueoqwieuqwertyqqweooqiwueoqiweuoiqwueoqwiueoqwiueoqwieuqwoeuwqoeuqoeuqoeiuqoeiu@gmail.com";
	    	assertEquals(1001, emailID.length());
	    	assertEquals(true, EmailCheck.INSTANCE.resolveEmailID(emailID, false, true).isValid());
	    }
	}
